rabbitmq:
  retry:
    count: 3
    delay: 5000
  dlq:
    ttl: 10000
  message:
    max.length: 10
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect